theme: minima
title: miscnotes
author: ug
# email: ug3.141@me.com
description: > # this means to ignore newlines until "baseurl:"
  Some musings about some things.
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ug3p141 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
